spring.application.name=fullstack-backend
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/fullstack
spring.datasource.username:root
spring.datasource.password:root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=vschanduuu@gmail.com
spring.mail.password=kthu plql pxcq msqa
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

WEATHER_API_KEY=417b386c4a86405571ff1d650a26548e


# Where the postal microservice is exposed. Use the gateway URL.
postal.client.base-url=http://localhost:8088/postal
# If you prefer direct service, change to: http://localhost:9090/postal

## Enable Feign and Circuit Breaker
spring.cloud.openfeign.circuitbreaker.enabled=true
#feign.circuitbreaker.enabled=true
## Force Feign to use Resilience4j
#spring.cloud.openfeign.circuitbreaker.enabled=true

# Circuit Breaker thresholds
resilience4j.circuitbreaker.instances.postalServiceCB.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.postalServiceCB.wait-duration-in-open-state=10000ms
resilience4j.circuitbreaker.instances.postalServiceCB.sliding-window-size=5
